tap "heroku/brew"
tap "homebrew/binary"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "koekeishiya/formulae"
tap "vitorgalvao/tiny-scripts"
cask "java"
brew "autoconf"
brew "gdbm"
brew "readline"
brew "aws-elasticbeanstalk"
brew "xz"
brew "python"
brew "awscli"
brew "bfg"
brew "cmatrix"
brew "doxygen"
brew "elixir"
brew "elixir-build"
brew "elm"
brew "exercism"
brew "freetype"
brew "gnupg"
brew "gpg-agent"
brew "icecast"
brew "libtool"
brew "imagemagick"
brew "lame"
brew "libevent"
brew "mas"
brew "ncmpcpp"
brew "pcre"
brew "pinentry-mac"
brew "postgresql"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "screenfetch"
brew "tmux"
brew "v8@3.15"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "koekeishiya/formulae/kwm"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "airfoil"
cask "airserver"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "blender"
cask "caffeine"
cask "dash"
cask "discord"
cask "firefox"
cask "gimp"
cask "google-earth-pro"
cask "gpg-suite"
cask "iterm2"
cask "keybase"
cask "kindlegen"
cask "macdown"
cask "postman"
cask "resilio-sync"
cask "screenhero"
cask "slack"
cask "spectacle"
cask "steam"
cask "sublime-text"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "vyprvpn"
mas "1Password 7", id: 1333542190
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Display Menu", id: 549083868
mas "Downcast", id: 668429425
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Spark", id: 1176895641
mas "Trello", id: 1278508951
mas "Twitter", id: 409789998
mas "Xcode", id: 497799835
